name: CI-CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
        
# CI        
    # - name: Build with Maven
    #   run: mvn -B package --file pom.xml

# SonarQube
    # - name : Run SonarQube
    #   run : ${{ secrets.SONAR_COMMAND }}

# CD
    - name: upload file
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_IP }}
        username: ${{ secrets.SSH_ID }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        source: "target/*.jar"
        target: "~/"
        rm: false

    - name: execute shell script
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_IP }}
        username: ${{ secrets.SSH_ID }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          sudo docker build -t sensor-data:latest ./ --build-arg FILE=target/sensor-data-0.0.1-SNAPSHOT.jar
          containers=$(sudo docker ps -a | grep sensor-data | awk '{print $1}')
          if [ -n "$containers" ]; then
            sudo docker stop $containers
            sudo docker rm $containers
          else
            echo "No containers with 'sensor-data' found."
          fi
          sudo docker run -d --name sensor-data-service --network=smoothing --restart always sensor-data
